# Generated by Django 4.2 on 2023-04-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_home',
            field=models.ImageField(blank=True, null=True, upload_to='home/'),
        ),
    ]
